[package]
name = "sked"
publish = false
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"

[features]
default = ["simple_logger"]

[dependencies]
chrono = "0.4.24"
log = "0.4.17"
lopdf = "0.31.0"
simple_logger = { version = "5.0.0", optional = true }
