[package]
name = "sked"
publish = false
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"

[features]
default = ["simple_logger"]

[dependencies]
chrono = "0.4.13"
log = "0.4.15"
lopdf = "0.27.0"
simple_logger = { version = "2.1.0", optional = true }

